-- Core document records for full-text search.
CREATE TABLE IF NOT EXISTS documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    path TEXT NOT NULL UNIQUE,
    title TEXT NOT NULL DEFAULT '',
    content TEXT NOT NULL DEFAULT '',
    checksum TEXT NOT NULL,
    search_vector TSVECTOR NOT NULL DEFAULT ''::tsvector,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Keep search_vector in sync on insert and content/title updates.
CREATE OR REPLACE FUNCTION documents_search_vector_update()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.search_vector :=
        setweight(to_tsvector('english', COALESCE(NEW.title, '')), 'A') ||
        setweight(to_tsvector('english', COALESCE(NEW.content, '')), 'B');
    NEW.updated_at := NOW();
    RETURN NEW;
END;
$$;

-- Recreate trigger safely on re-runs.
DROP TRIGGER IF EXISTS trg_documents_search_vector_update ON documents;

CREATE TRIGGER trg_documents_search_vector_update
BEFORE INSERT OR UPDATE OF title, content
ON documents
FOR EACH ROW
EXECUTE FUNCTION documents_search_vector_update();

-- GIN index supports fast FTS queries on search_vector.
CREATE INDEX IF NOT EXISTS ix_documents_search_vector
    ON documents
    USING GIN (search_vector);
