-- Indexing work queue for workers that claim jobs with FOR UPDATE SKIP LOCKED.
CREATE TABLE IF NOT EXISTS index_jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status TEXT NOT NULL DEFAULT 'pending',
    requested_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    claimed_at TIMESTAMPTZ,
    completed_at TIMESTAMPTZ,
    worker_id TEXT,
    error_message TEXT,
    CHECK (status IN ('pending', 'processing', 'completed', 'failed'))
);

-- Supports efficient pending-job polling in timestamp order.
CREATE INDEX IF NOT EXISTS ix_index_jobs_status_requested_at_id
    ON index_jobs (status, requested_at, id);
