-- Persist explicit source records as the foundation for source-aware ingestion.
CREATE TABLE IF NOT EXISTS sources (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    type TEXT NOT NULL,
    root_path TEXT NOT NULL UNIQUE,
    status TEXT NOT NULL DEFAULT 'active',
    last_indexed TIMESTAMPTZ,
    CHECK (type IN ('filesystem')),
    CHECK (status IN ('active', 'disabled', 'error'))
);

CREATE INDEX IF NOT EXISTS ix_sources_type_status
    ON sources (type, status);
